services:
  - type: web
    name: kufar-miniapp-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
